### ISSUE TITLE
Error:Exception has occurred: KeyError 'RANK'

### ISSUE THREAD

**Issue by Tristesse-stk** [zhiyuanyou/UniAD#10]
When I run the train_val.py in tools the error occurs in rank = int(os.environ["RANK"]) in dist_helper.py
The error is reported as follows.
Exception has occurred: KeyError
'RANK'

During handling of the above exception, another exception occurred:

  File "D:\Python\UniAD\utils\dist_helper.py", line 31, in setup_distributed
    rank = int(os.environ["RANK"])
  File "D:\Python\UniAD\tools\train_val.py", line 61, in main
    rank, world_size = utils.dist_helper.setup_distributed(port=config.port)
  File "D:\Python\UniAD\tools\train_val.py", line 343, in <module>
    main()

How to solve this problem?

**Comment by zhiyuanyou** [comment]
Well, I wonder how you run train_val.py? (the command you input to the terminal)



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 2, 2022 21:01 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [zhiyuanyou/UniAD] Error:Exception has occurred: KeyError 'RANK'(Issue #10)




 
When I run the train_val.py in tools the error occurs in rank = int(os.environ["RANK"]) in dist_helper.py
 The error is reported as follows.
 Exception has occurred: KeyError
 'RANK'
 
During handling of the above exception, another exception occurred:
 
File "D:\Python\UniAD\utils\dist_helper.py", line 31, in setup_distributed
 rank = int(os.environ["RANK"])
 File "D:\Python\UniAD\tools\train_val.py", line 61, in main
 rank, world_size = utils.dist_helper.setup_distributed(port=config.port)
 File "D:\Python\UniAD\tools\train_val.py", line 343, in 
 main()
 
How to solve this problem?

**Comment by zhiyuanyou** [comment]
I noticed that you used **Windows** rather than **Ubuntu**, which is our code based on.
I suggest you to try 
- add the root path (where the directories `tools & experiments` are in) to the Environment Variable ***PYTHONPATH***
- revise the `train_torch.sh` as follows

```
CUDA_VISIBLE_DEVICES=$2
python -m torch.distributed.launch --nproc_per_node=$1 ..\..\tools\train_val.py
```

Then you could use `sh train_torch.sh #NUM_GPUS #GPU_IDS` to train, *e.g.*, `sh train_torch.sh 1 0` means using GPU 0 to train.

**Comment by Ehteshamciitwah** [comment]
Hello, Thank you for your work.

i am implementing your GitHub repository on my Window system. I will use Pycharm IDE for debugging and understanding. While implementing I am getting the error  "Error:Exception has occurred: KeyError 'RANK'".
Instead of using terminal i am using Pycharm debug and run. 

I am looking for your response. Thank you

**Comment by zhiyuanyou** [comment]
> Hello, Thank you for your work.
> 
> i am implementing your GitHub repository on my Window system. I will use Pycharm IDE for debugging and understanding. While implementing I am getting the error "Error:Exception has occurred: KeyError 'RANK'". Instead of using terminal i am using Pycharm debug and run.
> 
> I am looking for your response. Thank you

Hi~ 

This error is caused because Windows does not have the Environment Variable "RANK". 
Our codes have been verified on Ubuntu, so I suggest you to switch to Ubuntu. 
Otherwise, it needs too many works to solve these problems.
